### ISSUE TITLE
python inference.py【error】

### ISSUE THREAD

**Issue by xs2021** [Tinysqua/UWAT-GAN#1]
Traceback (most recent call last):
  File "inference.py", line 62, in <module>
    main(args)
  File "inference.py", line 31, in main
    g_model_fine.load_state_dict(torch.load(args.Gen_F_path))
  File "/home/gongms/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Local_Enhancer:
        Missing key(s) in state_dict: "cache_module.0.weight", "cache_module.0.bias", "cache_module.3.weight", "cache_module.3.bias".

**Comment by xs2021** [comment]
已解决，添加strict=False：g_model_fine.load_state_dict(torch.load(args.Gen_F_path), strict=False)

**Comment by Benny0323** [comment]
Great!

> 已解决，添加strict=False：g_model_fine.load_state_dict(torch.load(args.Gen_F_path), strict=False)
